version: 2

jobs:
  build:
    docker:
      #- image: circleci/php:7.1.8-browsers
      - image: quay.io/ignited/php-nginx-fpm:7.0.19-latest

    working_directory: ~/mypal-pet-store
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          paths:
          - ./vendor
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: NodeJs install
          command: apk add --update nodejs

      - run:
          name: npm install
          command: apk add --update npm

      - run:
          name: Heroku version
          command: heroku --version

      - run:
          name: Setup Heroku
          command: wget -qO- http://cli-assets.heroku.com/install-ubuntu.sh | sh

      - run:
          name: composer install
          command: composer install -n --prefer-dist

#      - run:
#          name: angular install
#          command: cd angular-app/ng-frontend && npm install
#
#      - run:
#          name: angular build
#          command: cd angular-app/ng-frontend && npm run build

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run:
          name: php-testing
          command: vendor/bin/phpunit

      # now deploy
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git remote add heroku https://git.heroku.com/mypal-pet-store.git
              git push heroku master
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master