version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers

    working_directory: ~/mypal-pet-store
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          paths:
          - ./vendor
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: npm-install
          command: apk add --update nodejs

      - run:
          name: composer-install
          command: composer install -n --prefer-dist

      - run:
          name: angular-install
          command: cd angular-app/ng-frontend && npm install

      - run:
          name: angular-build
          command: cd angular-app/ng-frontend && npm run build

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run:
          name: php-testing
          command: vendor/bin/phpunit
